version: '3'
services:

  #NODE Service
  app:
    image: node:${NODE_V}
    container_name: server-mern
    restart: unless-stopped
    entrypoint: sh /init.sh
    tty: true
    working_dir: /server
    volumes:
      - ${PROJECT_PATH}:/server
      - ./init.sh:/init.sh
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - app-network

  #MongoDB   
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb-mern
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - app-network
    ports:
      - 27017:27017

  #Mongo-express
  mongo-express:
    image: mongo-express
    container_name: mongo-express-mern
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - app-network
    ports:
      - 8081:8081
    restart: unless-stopped

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  mongodb-data:
    name: mongodb-data